### ISSUE TITLE
After around 10-20 image the scrapper started only collecting Thunbnails of the image.

### ISSUE THREAD

**Issue by MoonetD** [ohyicong/Google-Image-Scraper#12]
Awsome code! But I could not get any more images in full size after about 10-20 images were scrapped. It only scrapped URL from "the encrypted-tbn0.gstatic.com" which is the thumbnail site for google. Do you know how can I fix that? Thank you!

**Comment by ohyicong** [comment]
hi what is your search phrase?

**Comment by MoonetD** [comment]
Hi! My search phrase was "splash art".

**Comment by ohyicong** [comment]
Hi, the code is working as it is. The reason why you see many images from "encrypted-tbn0.gstatic.com", it is because the original image has been removed so google couldn't load its full resolution. More info here https://support.google.com/webmasters/thread/122996062/how-long-do-encrypted-tbn0-gstatic-com-images-take-to-be-removed?hl=en
